# Generated by Django 4.0.10 on 2024-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
